title: Nikhil KO - Portfolio
author:
  name: Nikhil Kalamannil Oommen
  email: nikhiloommen12@gmail.com
email: nikhiloommen12@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Nikhil Kalamannil Oommen - Software Engineer - Portolio. Computer Science at University of Warwick. 
  Built using Jekyll, hosted on Github Pages.
url: "https://nikhil-ko.github.io"
baseurl: ""
github_username:  Nikhil-KO
